version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres:16.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

  server:
    container_name: server
    env_file: ./.env
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./src/:/server/src/
      - ./migrations/:/server/migrations/
    command: npm run start:debug
 
volumes:
  pgdata:
